// Code generated by "stringer --type=ErrorType --output=errors_string.go"; DO NOT EDIT.

package caesium

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrUnknown-0]
	_ = x[ErrInternal-1]
	_ = x[ErrInvalidQuery-2]
}

const _ErrorType_name = "ErrUnknownErrInternalErrInvalidQuery"

var _ErrorType_index = [...]uint8{0, 10, 21, 36}

func (i ErrorType) String() string {
	if i >= ErrorType(len(_ErrorType_index)-1) {
		return "ErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorType_name[_ErrorType_index[i]:_ErrorType_index[i+1]]
}
